### ISSUE TITLE
Trim对于多空格会有问题

### ISSUE THREAD

**Issue by thkx** [ArthurYung/keeper#3]
```ts
type A = Trim<' age  int      renamefrom:user_age'> // => age  int      renamefrom:user_age 
```
会保留中间的多个空格；从而影响 `ParseLine` 
```ts
type A = ParseLine<'age  int    renamefrom:user_age'> 
``` 
推断出 `age` 的类型为 `never`。
应该增加一个保留字符串保留一个空格的类型：
```ts
type TrimSpaces<Str extends string> = Str extends `${infer L} ${" "}${infer R}`
  ? TrimSpaces<`${L} ${R}`>
  : Str;
```

将`Trim`改为：
```ts
type Trim<Str extends string> = TrimLeft<TrimRight<TrimSpaces<Str>>>
```

**Comment by ArthurYung** [comment]
感谢提醒，但是我这里的Trim已经是分词后递归处理空格的，所以不需要再额外处理中间的空格，经过排查这里应该是遗漏的TrimLeft导致的，


修改前：
<img width="1290" alt="image" src="https://github.com/ArthurYung/keeper/assets/29910365/381bd59a-10aa-4e09-b752-22e4d2738507">

修改后
<img width="1188" alt="image" src="https://github.com/ArthurYung/keeper/assets/29910365/08c40916-8bce-4361-9b73-fe802dbc2b1f">

**Comment by ArthurYung** [comment]
https://github.com/ArthurYung/keeper/commit/5027e1e8dbf9c1181dfce0ff5bf82b2c443b431d
